platform :ios, '9.0'

target "ZJAlgorithm" do
pod 'AFNetworking','3.2.1'
pod 'Masonry','1.1.0'
pod 'YYKit', '~> 1.0.9'
pod 'MJRefresh','3.1.10'
pod 'IQKeyboardManager','6.3.0'
pod 'SDCycleScrollView','1.80'
pod 'SDWebImage','5.2.3'
pod 'TZImagePickerController', '~> 3.3.1'
pod 'FDFullscreenPopGesture','1.1'


end


